// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig, env } from 'prisma/config';

if (process.env.NODE_ENV === 'test') {
  config({ path: '.env.test' });
}

if (!(process.env.NODE_ENV === 'test')) {
  config();
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seeders/main.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
