name: Build, Docker and Deploy to VPS (Main)

on:
  push:
    branches: [main]

jobs:
  test-backend:
    uses: ./.github/workflows/main-test-backend.yml

  build-backend:
    needs: test-backend
    uses: ./.github/workflows/main-build-backend.yml

  build-frontend:
    uses: ./.github/workflows/main-build-frontend.yml

  docker-backend:
    needs: build-backend
    uses: ./.github/workflows/main-docker-backend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-frontend:
    needs: build-frontend
    uses: ./.github/workflows/main-docker-frontend.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-to-vps:
    needs: [docker-backend, docker-frontend]
    uses: ./.github/workflows/main-deploy-vps.yml
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
      COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
      EMAIL_PROVIDER_PASSWORD: ${{ secrets.EMAIL_PROVIDER_PASSWORD }}
      EMAIL_PROVIDER_USER: ${{ secrets.EMAIL_PROVIDER_USER }}
      EMAIL_PROVIDER_HOST: ${{ secrets.EMAIL_PROVIDER_HOST }}
      EMAIL_PROVIDER_PORT: ${{ secrets.EMAIL_PROVIDER_PORT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      ADMINISTRATOR_EMAIL: ${{ secrets.ADMINISTRATOR_EMAIL }}
      ADMINISTRATOR_PASSWORD: ${{ secrets.ADMINISTRATOR_PASSWORD }}
