/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as PrivateIndexRouteImport } from './routes/_private/index'
import { Route as PublicSignUpIndexRouteImport } from './routes/_public/sign-up/index'
import { Route as PublicSignInIndexRouteImport } from './routes/_public/sign-in/index'
import { Route as PrivateAdminIndexRouteImport } from './routes/_private/admin/index'
import { Route as PrivateResultSessionIdIndexRouteImport } from './routes/_private/result/$sessionId/index'
import { Route as PrivateGameModuleIdIndexRouteImport } from './routes/_private/game/$moduleId/index'
import { Route as PrivateAdminStudentsIndexRouteImport } from './routes/_private/admin/students/index'
import { Route as PrivateAdminModulesIndexRouteImport } from './routes/_private/admin/modules/index'
import { Route as PrivateAdminModulesModuleIdIndexRouteImport } from './routes/_private/admin/modules/$moduleId/index'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ranking/index.lazy').then((d) => d.Route))
const PrivateIndexRoute = PrivateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PublicSignUpIndexRoute = PublicSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivateAdminIndexRoute = PrivateAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/admin/index.lazy').then((d) => d.Route),
)
const PrivateResultSessionIdIndexRoute =
  PrivateResultSessionIdIndexRouteImport.update({
    id: '/result/$sessionId/',
    path: '/result/$sessionId/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/result/$sessionId/index.lazy').then(
      (d) => d.Route,
    ),
  )
const PrivateGameModuleIdIndexRoute =
  PrivateGameModuleIdIndexRouteImport.update({
    id: '/game/$moduleId/',
    path: '/game/$moduleId/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/game/$moduleId/index.lazy').then((d) => d.Route),
  )
const PrivateAdminStudentsIndexRoute =
  PrivateAdminStudentsIndexRouteImport.update({
    id: '/admin/students/',
    path: '/admin/students/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/students/index.lazy').then((d) => d.Route),
  )
const PrivateAdminModulesIndexRoute =
  PrivateAdminModulesIndexRouteImport.update({
    id: '/admin/modules/',
    path: '/admin/modules/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/modules/index.lazy').then((d) => d.Route),
  )
const PrivateAdminModulesModuleIdIndexRoute =
  PrivateAdminModulesModuleIdIndexRouteImport.update({
    id: '/admin/modules/$moduleId/',
    path: '/admin/modules/$moduleId/',
    getParentRoute: () => PrivateLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_private/admin/modules/$moduleId/index.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof PrivateIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/admin/': typeof PrivateAdminIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/sign-up/': typeof PublicSignUpIndexRoute
  '/admin/modules/': typeof PrivateAdminModulesIndexRoute
  '/admin/students/': typeof PrivateAdminStudentsIndexRoute
  '/game/$moduleId/': typeof PrivateGameModuleIdIndexRoute
  '/result/$sessionId/': typeof PrivateResultSessionIdIndexRoute
  '/admin/modules/$moduleId/': typeof PrivateAdminModulesModuleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivateIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/admin': typeof PrivateAdminIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/sign-up': typeof PublicSignUpIndexRoute
  '/admin/modules': typeof PrivateAdminModulesIndexRoute
  '/admin/students': typeof PrivateAdminStudentsIndexRoute
  '/game/$moduleId': typeof PrivateGameModuleIdIndexRoute
  '/result/$sessionId': typeof PrivateResultSessionIdIndexRoute
  '/admin/modules/$moduleId': typeof PrivateAdminModulesModuleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/_private/': typeof PrivateIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/_private/admin/': typeof PrivateAdminIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/_public/sign-up/': typeof PublicSignUpIndexRoute
  '/_private/admin/modules/': typeof PrivateAdminModulesIndexRoute
  '/_private/admin/students/': typeof PrivateAdminStudentsIndexRoute
  '/_private/game/$moduleId/': typeof PrivateGameModuleIdIndexRoute
  '/_private/result/$sessionId/': typeof PrivateResultSessionIdIndexRoute
  '/_private/admin/modules/$moduleId/': typeof PrivateAdminModulesModuleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ranking/'
    | '/admin/'
    | '/sign-in/'
    | '/sign-up/'
    | '/admin/modules/'
    | '/admin/students/'
    | '/game/$moduleId/'
    | '/result/$sessionId/'
    | '/admin/modules/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ranking'
    | '/admin'
    | '/sign-in'
    | '/sign-up'
    | '/admin/modules'
    | '/admin/students'
    | '/game/$moduleId'
    | '/result/$sessionId'
    | '/admin/modules/$moduleId'
  id:
    | '__root__'
    | '/_private'
    | '/_public'
    | '/_private/'
    | '/ranking/'
    | '/_private/admin/'
    | '/_public/sign-in/'
    | '/_public/sign-up/'
    | '/_private/admin/modules/'
    | '/_private/admin/students/'
    | '/_private/game/$moduleId/'
    | '/_private/result/$sessionId/'
    | '/_private/admin/modules/$moduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  RankingIndexRoute: typeof RankingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivateIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/sign-up/': {
      id: '/_public/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof PublicSignUpIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/admin/': {
      id: '/_private/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PrivateAdminIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/result/$sessionId/': {
      id: '/_private/result/$sessionId/'
      path: '/result/$sessionId'
      fullPath: '/result/$sessionId/'
      preLoaderRoute: typeof PrivateResultSessionIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/game/$moduleId/': {
      id: '/_private/game/$moduleId/'
      path: '/game/$moduleId'
      fullPath: '/game/$moduleId/'
      preLoaderRoute: typeof PrivateGameModuleIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/students/': {
      id: '/_private/admin/students/'
      path: '/admin/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof PrivateAdminStudentsIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/modules/': {
      id: '/_private/admin/modules/'
      path: '/admin/modules'
      fullPath: '/admin/modules/'
      preLoaderRoute: typeof PrivateAdminModulesIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/admin/modules/$moduleId/': {
      id: '/_private/admin/modules/$moduleId/'
      path: '/admin/modules/$moduleId'
      fullPath: '/admin/modules/$moduleId/'
      preLoaderRoute: typeof PrivateAdminModulesModuleIdIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivateIndexRoute: typeof PrivateIndexRoute
  PrivateAdminIndexRoute: typeof PrivateAdminIndexRoute
  PrivateAdminModulesIndexRoute: typeof PrivateAdminModulesIndexRoute
  PrivateAdminStudentsIndexRoute: typeof PrivateAdminStudentsIndexRoute
  PrivateGameModuleIdIndexRoute: typeof PrivateGameModuleIdIndexRoute
  PrivateResultSessionIdIndexRoute: typeof PrivateResultSessionIdIndexRoute
  PrivateAdminModulesModuleIdIndexRoute: typeof PrivateAdminModulesModuleIdIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivateIndexRoute: PrivateIndexRoute,
  PrivateAdminIndexRoute: PrivateAdminIndexRoute,
  PrivateAdminModulesIndexRoute: PrivateAdminModulesIndexRoute,
  PrivateAdminStudentsIndexRoute: PrivateAdminStudentsIndexRoute,
  PrivateGameModuleIdIndexRoute: PrivateGameModuleIdIndexRoute,
  PrivateResultSessionIdIndexRoute: PrivateResultSessionIdIndexRoute,
  PrivateAdminModulesModuleIdIndexRoute: PrivateAdminModulesModuleIdIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
  PublicSignUpIndexRoute: typeof PublicSignUpIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSignInIndexRoute: PublicSignInIndexRoute,
  PublicSignUpIndexRoute: PublicSignUpIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  RankingIndexRoute: RankingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
